language: android
android:
  components:
    - build-tools-23.0.1

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb
  - chmod +x gradlew
  
  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build